<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DesaSeeder extends Seeder
{
    public function run(): void
    {
        
        DB::table('desa')->truncate();
        DB::table('desa')->insert([
            ['kode_desa'=>'061001','kode_kecamatan'=>'061','nama_desa'=>'Bakung'],
            ['kode_desa'=>'061002','kode_kecamatan'=>'061','nama_desa'=>'Lorok'],
            ['kode_desa'=>'061003','kode_kecamatan'=>'061','nama_desa'=>'Parit'],
            ['kode_desa'=>'061004','kode_kecamatan'=>'061','nama_desa'=>'Purnajaya'],
            ['kode_desa'=>'061005','kode_kecamatan'=>'061','nama_desa'=>'Payakabung'],
            ['kode_desa'=>'061006','kode_kecamatan'=>'061','nama_desa'=>'Tanjung Baru'],
            ['kode_desa'=>'061007','kode_kecamatan'=>'061','nama_desa'=>'Tanjung Pering'],
            ['kode_desa'=>'061008','kode_kecamatan'=>'061','nama_desa'=>'Sungai Rambutan'],
            ['kode_desa'=>'061009','kode_kecamatan'=>'061','nama_desa'=>'Suak Batok'],
            ['kode_desa'=>'061010','kode_kecamatan'=>'061','nama_desa'=>'Timbangan'],
            ['kode_desa'=>'061011','kode_kecamatan'=>'061','nama_desa'=>'Suka Mulia'],
            ['kode_desa'=>'061012','kode_kecamatan'=>'061','nama_desa'=>'Pulau Kabal'],
            ['kode_desa'=>'061013','kode_kecamatan'=>'061','nama_desa'=>'Tanjung Pule'],
            ['kode_desa'=>'061014','kode_kecamatan'=>'061','nama_desa'=>'Permata Baru'],
            ['kode_desa'=>'061015','kode_kecamatan'=>'061','nama_desa'=>'Palem Raya'],
            ['kode_desa'=>'061016','kode_kecamatan'=>'061','nama_desa'=>'Pulau Semambu'],

            ['kode_desa'=>'060005','kode_kecamatan'=>'060','nama_desa'=>'Lubuk Sakti'],
            ['kode_desa'=>'060006','kode_kecamatan'=>'060','nama_desa'=>'Tanjung Gelam'],
            ['kode_desa'=>'060007','kode_kecamatan'=>'060','nama_desa'=>'Tanjung Agung'],
            ['kode_desa'=>'060008','kode_kecamatan'=>'060','nama_desa'=>'Ulak Bedil'],
            ['kode_desa'=>'060010','kode_kecamatan'=>'060','nama_desa'=>'Sudi Mampir'],
            ['kode_desa'=>'060011','kode_kecamatan'=>'060','nama_desa'=>'Penyandingan'],
            ['kode_desa'=>'060012','kode_kecamatan'=>'060','nama_desa'=>'Talang Aur'],
            ['kode_desa'=>'060013','kode_kecamatan'=>'060','nama_desa'=>'Ulak Banding'],
            ['kode_desa'=>'060014','kode_kecamatan'=>'060','nama_desa'=>'Muara Penimbung Ulu'],
            ['kode_desa'=>'060015','kode_kecamatan'=>'060','nama_desa'=>'Sakatiga'],
            ['kode_desa'=>'060016','kode_kecamatan'=>'060','nama_desa'=>'Tanjung Sejaro'],
            ['kode_desa'=>'060017','kode_kecamatan'=>'060','nama_desa'=>'Sakatiga Seberang'],
            ['kode_desa'=>'060019','kode_kecamatan'=>'060','nama_desa'=>'Tanjung Seteko'],
            ['kode_desa'=>'060027','kode_kecamatan'=>'060','nama_desa'=>'Ulak Segelung'],
            ['kode_desa'=>'060028','kode_kecamatan'=>'060','nama_desa'=>'Indralaya Mulya'],
            ['kode_desa'=>'060029','kode_kecamatan'=>'060','nama_desa'=>'Indralaya Raya'],
            ['kode_desa'=>'060030','kode_kecamatan'=>'060','nama_desa'=>'Indralaya Indah'],
            ['kode_desa'=>'060031','kode_kecamatan'=>'060','nama_desa'=>'Muara Penimbung Ilir'],
            ['kode_desa'=>'060032','kode_kecamatan'=>'060','nama_desa'=>'Tunas Aur'],
            ['kode_desa'=>'060033','kode_kecamatan'=>'060','nama_desa'=>'Sejaro Sakti'],

            ['kode_desa'=>'062001','kode_kecamatan'=>'062','nama_desa'=>'Tanjung Dayang Selatan'],
            ['kode_desa'=>'062002','kode_kecamatan'=>'062','nama_desa'=>'Mandi Angin'],
            ['kode_desa'=>'062003','kode_kecamatan'=>'062','nama_desa'=>'Sukaraja Baru'],
            ['kode_desa'=>'062004','kode_kecamatan'=>'062','nama_desa'=>'Sukaraja Lama'],
            ['kode_desa'=>'062005','kode_kecamatan'=>'062','nama_desa'=>'Tanjung Lubuk'],
            ['kode_desa'=>'062006','kode_kecamatan'=>'062','nama_desa'=>'Beti'],
            ['kode_desa'=>'062007','kode_kecamatan'=>'062','nama_desa'=>'Meranjat Ilir'],
            ['kode_desa'=>'062008','kode_kecamatan'=>'062','nama_desa'=>'Meranjat Ii'],
            ['kode_desa'=>'062009','kode_kecamatan'=>'062','nama_desa'=>'Meranjat I'],
            ['kode_desa'=>'062010','kode_kecamatan'=>'062','nama_desa'=>'Tebing Gerinting Selatan'],
            ['kode_desa'=>'062011','kode_kecamatan'=>'062','nama_desa'=>'Arisan Gading'],
            ['kode_desa'=>'062012','kode_kecamatan'=>'062','nama_desa'=>'Meranjat Iii'],
            ['kode_desa'=>'062013','kode_kecamatan'=>'062','nama_desa'=>'Tebing Gerinting Utara'],
            ['kode_desa'=>'062014','kode_kecamatan'=>'062','nama_desa'=>'Tanjung Dayang Utara'],

            ['kode_desa'=>'052001','kode_kecamatan'=>'052','nama_desa'=>'Suka Merindu'],
            ['kode_desa'=>'052002','kode_kecamatan'=>'052','nama_desa'=>'Saranglang'],
            ['kode_desa'=>'052003','kode_kecamatan'=>'052','nama_desa'=>'Kamal'],
            ['kode_desa'=>'052004','kode_kecamatan'=>'052','nama_desa'=>'Pulau Negara'],
            ['kode_desa'=>'052005','kode_kecamatan'=>'052','nama_desa'=>'Seribanding'],
            ['kode_desa'=>'052006','kode_kecamatan'=>'052','nama_desa'=>'Talang Pangeran Ulu'],
            ['kode_desa'=>'052007','kode_kecamatan'=>'052','nama_desa'=>'Ulak Kembahang I'],
            ['kode_desa'=>'052008','kode_kecamatan'=>'052','nama_desa'=>'Ulak Petangisan'],
            ['kode_desa'=>'052009','kode_kecamatan'=>'052','nama_desa'=>'Talang Pangeran Ilir'],
            ['kode_desa'=>'052010','kode_kecamatan'=>'052','nama_desa'=>'Ulak Kembahang Ii'],
            ['kode_desa'=>'052011','kode_kecamatan'=>'052','nama_desa'=>'Arisan Jaya'],

            ['kode_desa'=>'051001','kode_kecamatan'=>'051','nama_desa'=>'Maju Jaya'],
            ['kode_desa'=>'051002','kode_kecamatan'=>'051','nama_desa'=>'Naikan Tembakang'],
            ['kode_desa'=>'051003','kode_kecamatan'=>'051','nama_desa'=>'Pematang Bangsal'],
            ['kode_desa'=>'051004','kode_kecamatan'=>'051','nama_desa'=>'Sungai Lebung'],
            ['kode_desa'=>'051005','kode_kecamatan'=>'051','nama_desa'=>'Cahaya Marga'],
            ['kode_desa'=>'051006','kode_kecamatan'=>'051','nama_desa'=>'Mayapati'],
            ['kode_desa'=>'051007','kode_kecamatan'=>'051','nama_desa'=>'Kapuk'],
            ['kode_desa'=>'051008','kode_kecamatan'=>'051','nama_desa'=>'Segayam'],
            ['kode_desa'=>'051009','kode_kecamatan'=>'051','nama_desa'=>'Ulak Aurstanding'],
            ['kode_desa'=>'051010','kode_kecamatan'=>'051','nama_desa'=>'Harimau Tandang'],
            ['kode_desa'=>'051011','kode_kecamatan'=>'051','nama_desa'=>'Sungai Keli'],
            ['kode_desa'=>'051012','kode_kecamatan'=>'051','nama_desa'=>'Sungai Lebung Ulu'],
            ['kode_desa'=>'051013','kode_kecamatan'=>'051','nama_desa'=>'Lebak Pering'],
            ['kode_desa'=>'051014','kode_kecamatan'=>'051','nama_desa'=>'Sungai Ondok'],
            ['kode_desa'=>'051015','kode_kecamatan'=>'051','nama_desa'=>'Pematang Bungur'],

            ['kode_desa'=>'050016','kode_kecamatan'=>'050','nama_desa'=>'Aurstanding'],
            ['kode_desa'=>'050019','kode_kecamatan'=>'050','nama_desa'=>'Suka Rami'],
            ['kode_desa'=>'050020','kode_kecamatan'=>'050','nama_desa'=>'Palu'],
            ['kode_desa'=>'050021','kode_kecamatan'=>'050','nama_desa'=>'Muara Dua'],
            ['kode_desa'=>'050022','kode_kecamatan'=>'050','nama_desa'=>'Teluk Kecapi'],
            ['kode_desa'=>'050023','kode_kecamatan'=>'050','nama_desa'=>'Pelabuhan Dalam'],
            ['kode_desa'=>'050024','kode_kecamatan'=>'050','nama_desa'=>'Pemulutan Ulu'],
            ['kode_desa'=>'050025','kode_kecamatan'=>'050','nama_desa'=>'Pemulutan Ilir'],
            ['kode_desa'=>'050026','kode_kecamatan'=>'050','nama_desa'=>'Sungai Rasau'],
            ['kode_desa'=>'050027','kode_kecamatan'=>'050','nama_desa'=>'Pegayut'],
            ['kode_desa'=>'050028','kode_kecamatan'=>'050','nama_desa'=>'Ibul Besar I'],
            ['kode_desa'=>'050029','kode_kecamatan'=>'050','nama_desa'=>'Ibul Besar Ii'],
            ['kode_desa'=>'050030','kode_kecamatan'=>'050','nama_desa'=>'Ibul Besar Iii'],
            ['kode_desa'=>'050031','kode_kecamatan'=>'050','nama_desa'=>'Mekar Jaya'],
            ['kode_desa'=>'050032','kode_kecamatan'=>'050','nama_desa'=>'Lebung Jangkar'],
            ['kode_desa'=>'050033','kode_kecamatan'=>'050','nama_desa'=>'Kedukan Bujang'],
            ['kode_desa'=>'050034','kode_kecamatan'=>'050','nama_desa'=>'Rawa Jaya'],
            ['kode_desa'=>'050035','kode_kecamatan'=>'050','nama_desa'=>'Babatan Saudagar'],
            ['kode_desa'=>'050036','kode_kecamatan'=>'050','nama_desa'=>'Tanjung Pasir'],
            ['kode_desa'=>'050037','kode_kecamatan'=>'050','nama_desa'=>'Harapan'],
            ['kode_desa'=>'050038','kode_kecamatan'=>'050','nama_desa'=>'Pipa Putih'],
            ['kode_desa'=>'050039','kode_kecamatan'=>'050','nama_desa'=>'Sungai Buaya'],
            ['kode_desa'=>'050040','kode_kecamatan'=>'050','nama_desa'=>'Muara Baru'],
            ['kode_desa'=>'050041','kode_kecamatan'=>'050','nama_desa'=>'Sembadak'],
            ['kode_desa'=>'050042','kode_kecamatan'=>'050','nama_desa'=>'Simpang Pelabuhan Dalam'],

            ['kode_desa'=>'042001','kode_kecamatan'=>'042','nama_desa'=>'Tanjung Serian'],
            ['kode_desa'=>'042002','kode_kecamatan'=>'042','nama_desa'=>'Talang Dukun'],
            ['kode_desa'=>'042003','kode_kecamatan'=>'042','nama_desa'=>'Sungai Pinang Iii'],
            ['kode_desa'=>'042004','kode_kecamatan'=>'042','nama_desa'=>'Sungai Pinang'],
            ['kode_desa'=>'042005','kode_kecamatan'=>'042','nama_desa'=>'Sungai Pinang Ii'],
            ['kode_desa'=>'042006','kode_kecamatan'=>'042','nama_desa'=>'Serijabo'],
            ['kode_desa'=>'042007','kode_kecamatan'=>'042','nama_desa'=>'Penyandingan'],
            ['kode_desa'=>'042008','kode_kecamatan'=>'042','nama_desa'=>'Pinang Jaya'],
            ['kode_desa'=>'042009','kode_kecamatan'=>'042','nama_desa'=>'Sungai Pinang I'],
            ['kode_desa'=>'042010','kode_kecamatan'=>'042','nama_desa'=>'Pinang Mas'],
            ['kode_desa'=>'042011','kode_kecamatan'=>'042','nama_desa'=>'Sungai Pinang Lagati'],
            ['kode_desa'=>'042012','kode_kecamatan'=>'042','nama_desa'=>'Sungai Pinang Nibung'],
            ['kode_desa'=>'042013','kode_kecamatan'=>'042','nama_desa'=>'Serijabo Baru'],

            ['kode_desa'=>'041001','kode_kecamatan'=>'041','nama_desa'=>'Ketapang I'],
            ['kode_desa'=>'041002','kode_kecamatan'=>'041','nama_desa'=>'Jagalana'],
            ['kode_desa'=>'041003','kode_kecamatan'=>'041','nama_desa'=>'Kota Daro I'],
            ['kode_desa'=>'041004','kode_kecamatan'=>'041','nama_desa'=>'Kota Daro Ii'],
            ['kode_desa'=>'041005','kode_kecamatan'=>'041','nama_desa'=>'Rantau Panjang Ilir'],
            ['kode_desa'=>'041006','kode_kecamatan'=>'041','nama_desa'=>'Jagaraja'],
            ['kode_desa'=>'041007','kode_kecamatan'=>'041','nama_desa'=>'Sejangko I'],
            ['kode_desa'=>'041008','kode_kecamatan'=>'041','nama_desa'=>'Sungai Rotan'],
            ['kode_desa'=>'041009','kode_kecamatan'=>'041','nama_desa'=>'Sejangko Ii'],
            ['kode_desa'=>'041010','kode_kecamatan'=>'041','nama_desa'=>'Rantau Panjang Ulu'],
            ['kode_desa'=>'041011','kode_kecamatan'=>'041','nama_desa'=>'Ketapang Ii'],
            ['kode_desa'=>'041012','kode_kecamatan'=>'041','nama_desa'=>'Arisan Deras'],

            ['kode_desa'=>'040024','kode_kecamatan'=>'040','nama_desa'=>'Tanjung Temiang'],
            ['kode_desa'=>'040028','kode_kecamatan'=>'040','nama_desa'=>'Seridalam'],
            ['kode_desa'=>'040030','kode_kecamatan'=>'040','nama_desa'=>'Tanjung Raja'],
            ['kode_desa'=>'040031','kode_kecamatan'=>'040','nama_desa'=>'Tanjung Raja Barat'],
            ['kode_desa'=>'040032','kode_kecamatan'=>'040','nama_desa'=>'Tanjung Raja Utara'],
            ['kode_desa'=>'040035','kode_kecamatan'=>'040','nama_desa'=>'Talang Balai Baru I'],
            ['kode_desa'=>'040036','kode_kecamatan'=>'040','nama_desa'=>'Siring Alam'],
            ['kode_desa'=>'040037','kode_kecamatan'=>'040','nama_desa'=>'Tanjung Agas'],
            ['kode_desa'=>'040038','kode_kecamatan'=>'040','nama_desa'=>'Talang Balai Lama'],
            ['kode_desa'=>'040045','kode_kecamatan'=>'040','nama_desa'=>'Suka Pindah'],
            ['kode_desa'=>'040046','kode_kecamatan'=>'040','nama_desa'=>'Ulak Kerbau Lama'],
            ['kode_desa'=>'040047','kode_kecamatan'=>'040','nama_desa'=>'Ulak Kerbau Baru'],
            ['kode_desa'=>'040048','kode_kecamatan'=>'040','nama_desa'=>'Kerinjing'],
            ['kode_desa'=>'040049','kode_kecamatan'=>'040','nama_desa'=>'Tanjung Raja Timur'],
            ['kode_desa'=>'040050','kode_kecamatan'=>'040','nama_desa'=>'Belanti'],
            ['kode_desa'=>'040051','kode_kecamatan'=>'040','nama_desa'=>'Tanjung Raja Selatan'],
            ['kode_desa'=>'040052','kode_kecamatan'=>'040','nama_desa'=>'Talang Balai Baru Ii'],
            ['kode_desa'=>'040053','kode_kecamatan'=>'040','nama_desa'=>'Skonjing'],
            ['kode_desa'=>'040054','kode_kecamatan'=>'040','nama_desa'=>'Tanjung Harapan'],

            ['kode_desa'=>'031001','kode_kecamatan'=>'031','nama_desa'=>'Kumbang Ulu'],
            ['kode_desa'=>'031002','kode_kecamatan'=>'031','nama_desa'=>'Kumbang Ilir'],
            ['kode_desa'=>'031003','kode_kecamatan'=>'031','nama_desa'=>'Tanjung Alai'],
            ['kode_desa'=>'031004','kode_kecamatan'=>'031','nama_desa'=>'Muara Kumbang'],
            ['kode_desa'=>'031005','kode_kecamatan'=>'031','nama_desa'=>'Lubuk Rukam'],
            ['kode_desa'=>'031006','kode_kecamatan'=>'031','nama_desa'=>'Pandan Arang'],
            ['kode_desa'=>'031007','kode_kecamatan'=>'031','nama_desa'=>'Kandis I'],
            ['kode_desa'=>'031008','kode_kecamatan'=>'031','nama_desa'=>'Santapan Barat'],
            ['kode_desa'=>'031009','kode_kecamatan'=>'031','nama_desa'=>'Miji'],
            ['kode_desa'=>'031010','kode_kecamatan'=>'031','nama_desa'=>'Santapan Timur'],
            ['kode_desa'=>'031011','kode_kecamatan'=>'031','nama_desa'=>'Kandis Ii'],
            ['kode_desa'=>'031012','kode_kecamatan'=>'031','nama_desa'=>'Lubuk Segonang'],

            ['kode_desa'=>'030001','kode_kecamatan'=>'030','nama_desa'=>'Kelampaian'],
            ['kode_desa'=>'030002','kode_kecamatan'=>'030','nama_desa'=>'Suka Nanti'],
            ['kode_desa'=>'030003','kode_kecamatan'=>'030','nama_desa'=>'Rantau Alai'],
            ['kode_desa'=>'030004','kode_kecamatan'=>'030','nama_desa'=>'Kertabayang'],
            ['kode_desa'=>'030005','kode_kecamatan'=>'030','nama_desa'=>'Suka Maju'],
            ['kode_desa'=>'030006','kode_kecamatan'=>'030','nama_desa'=>'Sukamarga'],
            ['kode_desa'=>'030007','kode_kecamatan'=>'030','nama_desa'=>'Sanding Marga'],
            ['kode_desa'=>'030011','kode_kecamatan'=>'030','nama_desa'=>'Tanjung Mas'],
            ['kode_desa'=>'030012','kode_kecamatan'=>'030','nama_desa'=>'Lebung Bandung'],
            ['kode_desa'=>'030013','kode_kecamatan'=>'030','nama_desa'=>'Talang Sari'],
            ['kode_desa'=>'030019','kode_kecamatan'=>'030','nama_desa'=>'Sirah Pulau Kilip'],
            ['kode_desa'=>'030020','kode_kecamatan'=>'030','nama_desa'=>'Mekar Sari'],
            ['kode_desa'=>'030021','kode_kecamatan'=>'030','nama_desa'=>'Sukananti Baru'],

            ['kode_desa'=>'021001','kode_kecamatan'=>'021','nama_desa'=>'Tebedak I'],
            ['kode_desa'=>'021002','kode_kecamatan'=>'021','nama_desa'=>'Lubuk Bandung'],
            ['kode_desa'=>'021003','kode_kecamatan'=>'021','nama_desa'=>'Rengas I'],
            ['kode_desa'=>'021004','kode_kecamatan'=>'021','nama_desa'=>'Paya Besar'],
            ['kode_desa'=>'021005','kode_kecamatan'=>'021','nama_desa'=>'Talang Seleman'],
            ['kode_desa'=>'021006','kode_kecamatan'=>'021','nama_desa'=>'Payaraman Timur'],
            ['kode_desa'=>'021007','kode_kecamatan'=>'021','nama_desa'=>'Seri Kembang I'],
            ['kode_desa'=>'021008','kode_kecamatan'=>'021','nama_desa'=>'Tanjung Lalang'],
            ['kode_desa'=>'021009','kode_kecamatan'=>'021','nama_desa'=>'Seri Kembang Ii'],
            ['kode_desa'=>'021010','kode_kecamatan'=>'021','nama_desa'=>'Seri Kembang Iii'],
            ['kode_desa'=>'021011','kode_kecamatan'=>'021','nama_desa'=>'Tebedak Ii'],
            ['kode_desa'=>'021012','kode_kecamatan'=>'021','nama_desa'=>'Rengas Ii'],
            ['kode_desa'=>'021013','kode_kecamatan'=>'021','nama_desa'=>'Payaraman Barat'],

            ['kode_desa'=>'020008','kode_kecamatan'=>'020','nama_desa'=>'Seri Bandung'],
            ['kode_desa'=>'020012','kode_kecamatan'=>'020','nama_desa'=>'Seri Tanjung'],
            ['kode_desa'=>'020013','kode_kecamatan'=>'020','nama_desa'=>'Bangun Jaya'],
            ['kode_desa'=>'020014','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Tambak'],
            ['kode_desa'=>'020015','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Baru Petai'],
            ['kode_desa'=>'020016','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Batu Seberang'],
            ['kode_desa'=>'020017','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Atap'],
            ['kode_desa'=>'020018','kode_kecamatan'=>'020','nama_desa'=>'Limbang Jaya I'],
            ['kode_desa'=>'020024','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Laut'],
            ['kode_desa'=>'020025','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Pinang I'],
            ['kode_desa'=>'020026','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Batu'],
            ['kode_desa'=>'020027','kode_kecamatan'=>'020','nama_desa'=>'Pajar Bulan'],
            ['kode_desa'=>'020028','kode_kecamatan'=>'020','nama_desa'=>'Senuro Timur'],
            ['kode_desa'=>'020029','kode_kecamatan'=>'020','nama_desa'=>'Sentul'],
            ['kode_desa'=>'020030','kode_kecamatan'=>'020','nama_desa'=>'Burai'],
            ['kode_desa'=>'020031','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Batu Timur'],
            ['kode_desa'=>'020032','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Tambak Baru'],
            ['kode_desa'=>'020033','kode_kecamatan'=>'020','nama_desa'=>'Limbang Jaya Ii'],
            ['kode_desa'=>'020034','kode_kecamatan'=>'020','nama_desa'=>'Senuro Barat'],
            ['kode_desa'=>'020035','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Pinang Ii'],
            ['kode_desa'=>'020036','kode_kecamatan'=>'020','nama_desa'=>'Tanjung Atap Barat'],

            ['kode_desa'=>'012001','kode_kecamatan'=>'012','nama_desa'=>'Ulak Kembahang'],
            ['kode_desa'=>'012002','kode_kecamatan'=>'012','nama_desa'=>'Lubuk Keliat'],
            ['kode_desa'=>'012003','kode_kecamatan'=>'012','nama_desa'=>'Embacang'],
            ['kode_desa'=>'012004','kode_kecamatan'=>'012','nama_desa'=>'Betung I'],
            ['kode_desa'=>'012005','kode_kecamatan'=>'012','nama_desa'=>'Kasih Raja'],
            ['kode_desa'=>'012006','kode_kecamatan'=>'012','nama_desa'=>'Talang Tengah'],
            ['kode_desa'=>'012007','kode_kecamatan'=>'012','nama_desa'=>'Ketiau'],
            ['kode_desa'=>'012008','kode_kecamatan'=>'012','nama_desa'=>'Betung Ii'],
            ['kode_desa'=>'012009','kode_kecamatan'=>'012','nama_desa'=>'Payalingkung'],
            ['kode_desa'=>'012010','kode_kecamatan'=>'012','nama_desa'=>'Talang Tengah Laut'],

            ['kode_desa'=>'011001','kode_kecamatan'=>'011','nama_desa'=>'Ibul Dalam'],
            ['kode_desa'=>'011002','kode_kecamatan'=>'011','nama_desa'=>'Beringin Dalam'],
            ['kode_desa'=>'011003','kode_kecamatan'=>'011','nama_desa'=>'Kuang Dalam Barat'],
            ['kode_desa'=>'011004','kode_kecamatan'=>'011','nama_desa'=>'Lubuk Tunggal'],
            ['kode_desa'=>'011005','kode_kecamatan'=>'011','nama_desa'=>'Ulak Segara'],
            ['kode_desa'=>'011006','kode_kecamatan'=>'011','nama_desa'=>'Tambang Rambang'],
            ['kode_desa'=>'011007','kode_kecamatan'=>'011','nama_desa'=>'Tangai'],
            ['kode_desa'=>'011008','kode_kecamatan'=>'011','nama_desa'=>'Tanjung Miring'],
            ['kode_desa'=>'011009','kode_kecamatan'=>'011','nama_desa'=>'Kayu Ara'],
            ['kode_desa'=>'011010','kode_kecamatan'=>'011','nama_desa'=>'Tanjung Bulan'],
            ['kode_desa'=>'011011','kode_kecamatan'=>'011','nama_desa'=>'Sunur'],
            ['kode_desa'=>'011012','kode_kecamatan'=>'011','nama_desa'=>'Kuang Dalam Timur'],
            ['kode_desa'=>'011013','kode_kecamatan'=>'011','nama_desa'=>'Sukananti'],

            ['kode_desa'=>'010004','kode_kecamatan'=>'010','nama_desa'=>'Munggu'],
            ['kode_desa'=>'010005','kode_kecamatan'=>'010','nama_desa'=>'Seri Menanti'],
            ['kode_desa'=>'010006','kode_kecamatan'=>'010','nama_desa'=>'Rantau Sialang'],
            ['kode_desa'=>'010007','kode_kecamatan'=>'010','nama_desa'=>'Kuang Anyar'],
            ['kode_desa'=>'010009','kode_kecamatan'=>'010','nama_desa'=>'Kasah'],
            ['kode_desa'=>'010011','kode_kecamatan'=>'010','nama_desa'=>'Muara Kuang'],
            ['kode_desa'=>'010012','kode_kecamatan'=>'010','nama_desa'=>'Tanabang Ilir'],
            ['kode_desa'=>'010013','kode_kecamatan'=>'010','nama_desa'=>'Seri Kembang'],
            ['kode_desa'=>'010014','kode_kecamatan'=>'010','nama_desa'=>'Naga Sari'],
            ['kode_desa'=>'010015','kode_kecamatan'=>'010','nama_desa'=>'Suka Cinta'],
            ['kode_desa'=>'010016','kode_kecamatan'=>'010','nama_desa'=>'Kelampadu'],
            ['kode_desa'=>'010017','kode_kecamatan'=>'010','nama_desa'=>'Sukajadi'],
            ['kode_desa'=>'010018','kode_kecamatan'=>'010','nama_desa'=>'Rama Kasih'],
            ['kode_desa'=>'010019','kode_kecamatan'=>'010','nama_desa'=>'Tanabang Ulu'],
        ]);
    }
}
